### ISSUE TITLE
Nova 4: partials.logo not found

### ISSUE THREAD

**Issue by phlisg** [cube-agency/nova-google2fa#1]
Hello,

Thank you for your package.

After installing & configuring the package, my application is throwing an error complaining that a view doesn't exist. I suspect this is Nova 3 code.

https://github.com/cube-agency/nova-google2fa/blob/69f7cd5e56884b66af6ffaf33edb0c1ac538187c/resources/views/layouts/main.blade.php#L27

Removing the line fixes the issue.

**Comment by phlisg** [comment]
Created simple PR to fix this #2

**Comment by miks** [comment]
thanks

**Comment by phlisg** [comment]
Thank you for the very ultra quick merge!
