### ISSUE TITLE
Error on registration: The payload is invalid

### ISSUE THREAD

**Issue by JorgenSolli** [cube-agency/nova-google2fa#11]
Thank you for this package! It works great, except for this one issue I encountered:

During registration, I would get this Exception "The payload is invalid"
After some digging, I found that the google2fa_secret column's text limit is not long enough for new encrypt standards.

The column needs to be updated with a new length to work.
```
$table->string('google2fa_secret', 255)->nullable();
```

**Comment by miks** [comment]
@JorgenSolli how long it needs to be? By default it's already have 255 varchar at least with mysql.

**Comment by JorgenSolli** [comment]
@miks Strange... Mine was set to 191. updating it to 255 solved it. I believe the encrypted value was 197 chars long if I remember correctly.

**Comment by JorgenSolli** [comment]
I had a look and it seems that 255 is indeed the default value. So this might be an issue related to my installation only.
The issue can probably be ignored.

**Comment by miks** [comment]
ok.

**Comment by JorgenSolli** [comment]
I found the root cause. I had specified `Schema::defaultStringLength(191);` in the AppServiceProvider.
That was a fix for something long ago when upgrading to Laravel 5.4.

Just in case someone else comes across this down the line :)

**Comment by takdw** [comment]
> Just in case someone else comes across this down the line :)

Had the same EXACT issue... same root cause. Thanks!
