### ISSUE TITLE
Documents Revision - For Adding To Custom Models

### ISSUE THREAD

**Issue by kinger251285** [cube-agency/nova-google2fa#7]
This may be specific to my project. 

Laravel - 9.2
Nova - 4.0

To add this package to a custom model (my case 'Admin') i needed to add the following:

`
use Illuminate\Database\Eloquent\Relations\HasOne;
`

and also define the foreign key in my relationship as below:

`
public function user2fa(): HasOne
    {
        return $this->hasOne(User2fa::class, 'user_id');
    }
`

Without this it threw a http 500 error when trying to login to Nova via my custom model. I couldn't see this information in the docs.

**Comment by miks** [comment]
fixed
